### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Sysca11** [Sysca11/BedrockKit#6]
- [ ] restrict land lowest y position(land will not include blocks whose posY is below 30)
- [ ] restrict land dimension(you cant claim lands in some dimensions)
- [ ] add chat/command filter for lua,DONT process every chat/command in lua,it's inefficient.
- [ ] add chat/command rate limit
- [ ] add maintaining_list.txt which records where the hard-coded offsets are
- [ ] investigate why lua menu is sometimes not responding.
- [ ] investigate random crashes when a player disconnect abnormally and rejoin the server
